---
main:
- name: Home
  url: ""
  weight: 1
- name: About Me
  url: about/
  weight: 2
- name: Blog
  url: blog/
  weight: 3
- name: Contact
  url: contact/
  weight: 4
footer:
- name: About Me
  url: about/
  weight: 1
- name: Privacy Policy
  url: privacy-policy/
  weight: 2
- name: Imprint
  url: imprint/
  weight: 3
