[project]
name = "embedded-focus-site"
version = "0.1.0"
description = "Embedded Focus Website"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
]

[dependency-groups]
dev = [
    "pyright>=1.1.394",
    "ruff>=0.9.6",
]
